#!/bin/sh

header=$(boot2docker ssh df -h | grep Filesystem)
before=$(boot2docker ssh df -h | grep /dev/sda1 | grep aufs 2>/dev/null)

echo "        $header"
echo "Before: $before"
echo

echo "Deleting stopped containers"
docker ps -aq | xargs docker rm

echo "Deleting untagged images"
docker images | grep '^<none' | awk '{print $3}' | xargs docker rmi -f

echo "Docker images with size >500MB"
docker images | grep --color=none '[0-9] GB'
docker images | grep --color=none '[5-9]..\.. MB'

echo
after=$(boot2docker ssh df -h | grep /dev/sda1 | grep aufs 2>/dev/null)
echo "        $header"
echo "Before: $before"
echo "After:  $after"
