#!/bin/sh

df_h() {
    boot2docker ssh df -h 2>/dev/null || df -h
}
header=$(df_h | grep Filesystem)
before=$(df_h | grep /var/lib/docker)

echo "        $header"
echo "Before: $before"
echo

echo "Deleting stopped containers"
docker ps -aq | xargs docker rm

echo "Deleting untagged images"
docker images | grep '^<none' | awk '{print $3}' | xargs docker rmi -f

echo "Docker images with size >500MB"
docker images | grep --color=none '[0-9] GB'
docker images | grep --color=none '[5-9]..\.. MB'

echo
after=$(df_h | grep /var/lib/docker)
echo "        $header"
echo "Before: $before"
echo "After:  $after"
