#!/bin/bash

if [ -z "${1}" ]; then
    echo "Usage: $(basename ${0}) service"
    echo
    for service in $(cat fig.yml | grep '^[a-z]' | cut -d: -f1); do
        echo "- $(basename ${0}) $service"
    done
    exit 1
fi

set -e

fig stop ${NAME}
fig up --no-deps -d ${NAME}
fig logs ${NAME}
